<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>.icon\Graphicloads-Polygon-Check.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="SVNMergeCheckerUI.Tests\**" />
    <EmbeddedResource Remove="SVNMergeCheckerUI.Tests\**" />
    <None Remove="SVNMergeCheckerUI.Tests\**" />
  </ItemGroup>

  <ItemGroup>
    <Content Include=".icon\Graphicloads-Polygon-Check.ico" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="SVNMergeCheckerUI.Tests" />
  </ItemGroup>

</Project>